# Known good environment on ubuntu 20.04
# When new dependencies are added:
# conda env export --no-builds > conda.yaml
name: wikigit
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.8.5
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - chardet==4.0.0
    - idna==2.10
    - requests==2.25.1
    - urllib3==1.26.3
